export enum QuestionError {
    TITLE_INVALID,
    NOT_ENOUGH_ANSWER_OPTIONS,
    NO_CORRECT_ANSWER,
    ANSWER_OPTION_INVALID,
    RIGHT_ANSWER_SCREEN_TIME_INVALID,
    WRONG_ANSWER_SCREEN_TIME_INVALID,
    IMAGE_SEARCH_AREAS_MISSING
}
